/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chapter31.demoapp.ui;

import chapter31.demoapp.service.App;
import java.awt.Toolkit;

/**
 *
 * @author thetkhine
 */
public class MainAppForm extends javax.swing.JFrame {

    /**
     * Creates new form MainAppForm
     */
    LoginDialog dialog;
    AddNewItemForm newItemForm = new AddNewItemForm();
    AllItemForm allItemForm = new AllItemForm();
    SaleItemForm saleItemForm = new SaleItemForm();
    public MainAppForm() {
        initComponents();
        
        this.dialog = new LoginDialog(this, true);
        //dialog.setVisible(true);
        
    
        this.setSize(Toolkit.getDefaultToolkit().getScreenSize());
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuNewItem = new javax.swing.JMenuItem();
        mnuAllItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuSaleItem = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        mnuNewItem.setText("New Item");
        mnuNewItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNewItemActionPerformed(evt);
            }
        });
        jMenu1.add(mnuNewItem);

        mnuAllItem.setText("All Item");
        mnuAllItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAllItemActionPerformed(evt);
            }
        });
        jMenu1.add(mnuAllItem);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Shop");

        mnuSaleItem.setText("Sale Item");
        mnuSaleItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSaleItemActionPerformed(evt);
            }
        });
        jMenu2.add(mnuSaleItem);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 838, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 683, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuNewItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNewItemActionPerformed
        // TODO add your handling code here:
        this.newItemForm.setVisible(true);
    }//GEN-LAST:event_mnuNewItemActionPerformed

    private void mnuAllItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAllItemActionPerformed
        // TODO add your handling code here:
        this.allItemForm.setVisible(true);
        this.allItemForm.renderItems(App.getInstance().itemService.getAllItems());
    }//GEN-LAST:event_mnuAllItemActionPerformed

    private void mnuSaleItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSaleItemActionPerformed
        // TODO add your handling code here:
        this.saleItemForm.setVisible(true);
        this.saleItemForm.initItem();
    }//GEN-LAST:event_mnuSaleItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainAppForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainAppForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainAppForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainAppForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MainAppForm appForm = new MainAppForm();
                appForm.setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem mnuAllItem;
    private javax.swing.JMenuItem mnuNewItem;
    private javax.swing.JMenuItem mnuSaleItem;
    // End of variables declaration//GEN-END:variables
}
