/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jdbc.app;

/**
 *
 * @author thetkhine
 */
public class MainFrame extends javax.swing.JFrame {

    MovieForm movieForm = new MovieForm();
    ActorInMovieFrame actorInMovieForm = new ActorInMovieFrame();
    MovieSearchForm movieSearchForm = new MovieSearchForm();
    LoginDialog dialog;
    RegisterUser registerUser = new RegisterUser();
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
           
        this.dialog = new LoginDialog(this, true);
        dialog.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuMovie = new javax.swing.JMenuItem();
        mnuSearchMovie = new javax.swing.JMenuItem();
        mnuActorInMovie = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuRegisterUser = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("File");

        mnuMovie.setText("Movie");
        mnuMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuMovieActionPerformed(evt);
            }
        });
        jMenu1.add(mnuMovie);

        mnuSearchMovie.setText("Search Movie");
        mnuSearchMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSearchMovieActionPerformed(evt);
            }
        });
        jMenu1.add(mnuSearchMovie);

        mnuActorInMovie.setText("Actor In Movie");
        mnuActorInMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuActorInMovieActionPerformed(evt);
            }
        });
        jMenu1.add(mnuActorInMovie);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        mnuRegisterUser.setText("Register User");
        mnuRegisterUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRegisterUserActionPerformed(evt);
            }
        });
        jMenu2.add(mnuRegisterUser);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 833, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuMovieActionPerformed
        // TODO add your handling code here:
        this.movieForm.setVisible(true);
    }//GEN-LAST:event_mnuMovieActionPerformed

    private void mnuActorInMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuActorInMovieActionPerformed
        // TODO add your handling code here:
        this.actorInMovieForm.setVisible(true);
    }//GEN-LAST:event_mnuActorInMovieActionPerformed

    private void mnuSearchMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSearchMovieActionPerformed
        // TODO add your handling code here:
        this.movieSearchForm.setVisible(true);
    }//GEN-LAST:event_mnuSearchMovieActionPerformed

    private void mnuRegisterUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRegisterUserActionPerformed
        // TODO add your handling code here:
        this.registerUser.setVisible(true);
    }//GEN-LAST:event_mnuRegisterUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem mnuActorInMovie;
    private javax.swing.JMenuItem mnuMovie;
    private javax.swing.JMenuItem mnuRegisterUser;
    private javax.swing.JMenuItem mnuSearchMovie;
    // End of variables declaration//GEN-END:variables
}
